travis: disable osx for now
Job fails trying to donwload boost:

==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.7: 281 files, 10.4MB
==> Installing gtk-doc dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.66.0.sierra.bottle.tar.gz
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "boost"
Download failed: https://homebrew.bintray.com/bottles/boost-1.66.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.66.0 --libdir=/usr/local/Cellar/boost/1.66.0/lib --without-icu --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.66.0 --libdir=/usr/local/Cellar/boost/1.66.0/lib -d2 -j3 --layout=tagged --user-config=user-config.jam -sNO_LZMA=1 install threading=multi,single link=shared,static cxxflags=-std=c++11 cxxflags=-stdlib=libc++ linkflags=-stdlib=libc++
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated